### ISSUE TITLE
replace: suffix is added into index, but there is no alias

### ISSUE THREAD

**Issue by niwatolli3** [embulk/embulk-output-elasticsearch#42]
Hi, I love this plugin.

I used replace:, but suffix is added into index:
I need to add alias after insertion is finished.

Can I use this feature or are we need to develop this feature?

Thanks,

**Comment by sakama** [comment]
@niwatolli3 Hi.

> but suffix is added into index

Plugin doesn't add suffix to existing index. This index is just a newly created one.

This plugin works with following process when **replace mode**.
1. insert data into new index(will be newly created by plugin)
2. re assign alias from old index to new index
3. drop old index

There is a possibility that something failure(bad network connection, invalid data...) happens while 1.  At this time, plugin user will lost both of existing data and new data.
By processing 1-2-3, one of them will be kept in Elasticsearch.

So I think current logic is the best way to provide replace mode.

> Can I use this feature or are we need to develop this feature?

Is it not enough that you set alias name to `index` option?
```yaml
out:
  type: elasticsearch
  mode: replace
  index: <alias name> # plugin generates index name like <index>_%Y%m%d-%H%M%S
  ...
```
https://github.com/muga/embulk-output-elasticsearch#replace
