### ISSUE TITLE
Can specified a datatype? ex nested datatype

### ISSUE THREAD

**Issue by keiaihara** [embulk/embulk-output-elasticsearch#50]
Thanks help.

**Comment by sakama** [comment]
@keiaihara Could you explain more detail?
I couldn't understand your intention.

**Comment by keiaihara** [comment]
@sakama 

I just would like to import Mysql data to Elasticsearch, mapping each fields as I determine datatype and analyzer.

ref https://www.elastic.co/guide/en/elasticsearch/reference/6.2/mapping-types.html

**Comment by sakama** [comment]
I guess you want to specify column option like embulk-iput-mysql.
Unfortunately, it's impossible.
```yaml
out:
  type: elasticsearch
  column_options:
    col1: {type: long}
    col2: {type: string, timestamp_format: "%H:%M:%S", timezone: "+0900"}
```

embulk-output-elasticsearch generally uses schema passed from Embulk Input(or File Input plugin).
If column type is treated as "long" in input plugin, it will also be a "long" in embulk-output-elasticsearch.
You need to convert column type at Input plugin or Filter plugin.
