### ISSUE TITLE
Not support es 7.x

### ISSUE THREAD

**Issue by yazGR** [embulk/embulk-output-elasticsearch#57]
In es 7.4 not let me put a custom \_type, only \_doc and when I try to use the configuration with that index_type, it send me a message that I can't use "_".

```yaml
out:
  type: elasticsearch
  mode: replace
  index: results-201903
  index_type: _doc
  nodes:
    - { host: db, port: '9200' }
```
